services:
  app:
    build: .
    env_file: scripts/auth.env
    container_name: boiler-plate
    command: poetry run uvicorn src.main:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - 5001:80
    volumes:
      - .:/app